version: "3.8"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root@1234
      MYSQL_DATABASE: employeedb
    networks:
      spring-network:

  docker-demo:
    container_name: docker-demo
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    networks:
      spring-network:
    restart: on-failure






networks:
  spring-network: